Repository La-Brujula/front, pull requests merged in 2024-02, with the labels that each got.

#32 Cambios a footer #30
  src/shared/components/socials.jsx
  src/shared/navigation/footer.jsx
Labels: simple, change

#31 Actualizar cuadrícula de búsqueda y contador de resultados #27
  src/modules/search/components/nameSearchField.jsx
  src/modules/search/pages/results.jsx
Labels: simple, change

#33 29-cambios-a-perfil
  src/modules/auth/pages/basicInfo.jsx
  src/modules/profile/components/contactInfo.jsx
  src/modules/profile/components/profileHeader.jsx
  src/modules/profile/pages/landing.jsx
  src/modules/search/pages/results.jsx
Labels: simple, change

#34 blank query doesn't fetch results
  src/modules/search/pages/results.jsx
  src/shared/hooks/useSearch.js
Labels: technical, change

#38 Cambios-8-02-24
  src/modules/auth/components/activityLookupField.jsx
  src/modules/auth/pages/areas.jsx
  src/modules/auth/pages/base.jsx
  src/modules/auth/pages/basicInfo.jsx
  src/modules/auth/pages/contact.jsx
  src/modules/auth/pages/passwordReset.jsx
  src/modules/auth/pages/summary.jsx
  src/modules/landing/components/currentUserBadge.jsx
  src/modules/landing/components/searchModules.jsx
  src/modules/profile/components/profileBadge.jsx
  src/modules/profile/components/profileHeader.jsx
  src/modules/profile/pages/userProfile.jsx
  src/modules/search/components/nameSearchField.jsx
  src/modules/search/components/referenceField.jsx
  src/modules/search/pages/results.jsx
  src/modules/search/pages/searchByCategory.jsx
  src/modules/search/pages/subcategory.jsx
  src/modules/search/router.jsx
  src/shared/components/errorMessage.jsx
  src/shared/components/textSelect.jsx
  src/shared/hooks/useSearch.js
Labels: bug, simple, change

#40 35-nuevo-diseño-de-directorios
  .vscode/extensions.json
  package.json
  public/guias/thumbnails/Portada_Aguascalientes.jpeg
  public/guias/thumbnails/Portada_Centro.jpeg
  public/guias/thumbnails/Portada_Guanajuato.jpeg
  public/guias/thumbnails/Portada_Noroeste.jpeg
  public/guias/thumbnails/Portada_Norte.jpeg
  public/guias/thumbnails/Portada_Occidente.jpeg
  public/guias/thumbnails/Portada_Sureste.jpeg
  public/guias/thumbnails/Portadas_aguascalientes.png
  public/guias/thumbnails/Portadas_centro.png
  public/guias/thumbnails/Portadas_guanajuato.png
  public/guias/thumbnails/Portadas_noroeste.png
  public/guias/thumbnails/Portadas_norte.png
  public/guias/thumbnails/Portadas_occidente.png
  public/guias/thumbnails/Portadas_sureste.png
  src/modules/guides/page.jsx
  src/modules/landing/components/downloadGuides.jsx
  src/modules/landing/components/strip.jsx
  src/modules/landing/components/strip.module.css
  src/modules/profile/components/profileBadge.jsx
  src/modules/profile/components/profileBar.jsx
  src/modules/profile/components/profileHeader.jsx
  src/modules/search/components/extraFilters.jsx
  src/modules/search/components/nameSearchField.jsx
  src/modules/search/components/userCard.jsx
  src/modules/search/pages/searchByCategory.jsx
  src/shared/constants/guides.json
  vite.config.js
  yarn.lock
Labels: simple, change

#41 added "build" workflow definition
  .github/workflows/build.yml
Labels: enhancement

#47 fixes Agregar logo de tequila a sección aliados #46
  public/img/aliades/Logo_Tequila_Jalisco.svg
  src/shared/constants/aliades.json
Labels: enhancement, simple

#49 fix [BUG] Error al acceder a perfil con servicio de becario #48
  src/modules/profile/pages/landing.jsx
Labels: bug

#53 fix Título de actividad para no binario #50
  src/shared/utils/areaUtils.js
Labels: bug, technical

#54 fix Cambio de nombre a actividad #43
  src/shared/constants/areas.json
Labels: simple, change

#62 [BUG] Eliminar actividad del registro borra la equivocada #61
  src/modules/auth/components/languageListForm.tsx
  src/modules/auth/hooks/useAreasReducer.ts
  src/modules/auth/pages/areas.tsx
  src/modules/landing/components/aliados.tsx
  src/modules/landing/components/bannerAnuncios.tsx
  src/modules/landing/components/quotesSlider.tsx
  src/modules/search/components/categorias.tsx
Labels: bug, technical

#71 fix [BUG] Búsqueda por especialidades áreas no válidas #66
  src/modules/search/components/categorias.tsx
  src/modules/search/pages/subcategory.tsx
  src/modules/search/router.tsx
  src/shared/constants/areas.ts
Labels: bug, technical

#72 added tailwind prettier plugin
  package.json
  yarn.lock
Labels: change, dependencies

#68 67 refactorizar módulo about para usar i18n
  i18next-parser.config.mjs
  public/locales/about/en.json
  public/locales/about/es.json
  public/locales/about/fr.json
  public/locales/navigation/en.json
  public/locales/navigation/es.json
  public/locales/navigation/fr.json
  src/i18n.ts
  src/modules/about/components/credits.tsx
  src/modules/about/components/hero.tsx
Labels: simple, change
