Repository La-Brujula/front, pull requests merged in 2024-03, with the labels that each got.

#84 added error page boundary
  public/locales/common/en.json
  public/locales/common/es.json
  public/locales/common/fr.json
  src/routes.tsx
  src/shared/navigation/errorHandler.tsx
  tailwind.config.cjs
Labels: enhancement, simple

#70 64 refactorizar módulo landing para usar i18n
  .husky/pre-commit
  .vscode/extensions.json
  .vscode/settings.json
  public/locales/landing/en.json
  public/locales/landing/es.json
  public/locales/landing/fr.json
  public/locales/quotes/en.json
  public/locales/quotes/es.json
  public/locales/quotes/fr.json
  src/modules/landing/components/downloadGuides.tsx
  src/modules/landing/components/heroSection.tsx
  src/modules/landing/components/quoteSlide.tsx
  src/modules/landing/components/quotesSlider.tsx
  src/shared/constants/quotes.json
Labels: simple, change

#86 completes Refactorizar módulo deleteAccount para usar i18n #80
  public/locales/deleteAccount/en.json
  public/locales/deleteAccount/es.json
  public/locales/deleteAccount/fr.json
  src/modules/deleteAccount/page.tsx
Labels: enhancement, simple

#87 added country select and refactored basic info page to input component
  public/locales/auth/en.json
  public/locales/auth/es.json
  public/locales/auth/fr.json
  public/locales/countries/en.json
  public/locales/countries/es.json
  public/locales/countries/fr.json
  src/modules/auth/pages/basicInfo.tsx
  src/modules/contact/components/contactForm.tsx
  src/shared/components/countrySelect.tsx
  src/shared/components/countrySelectCodes.tsx
  src/shared/components/input.tsx
  src/shared/components/textSelect.tsx
  src/shared/constants/countryCodes.json
Labels: enhancement, technical
